/**
 * Strategic Payment Integration Service
 * 
 * This service manages the interface between the NGO platform and 
 * high-resilience payment gateways (Yoco, PayFast).
 */

export interface PaymentIntent {
  amount: number;
  currency: string;
  metadata: {
    donorEmail: string;
    donorName: string;
    donationType: 'one-time' | 'monthly';
    programId?: string;
  };
}

export const paymentService = {
  /**
   * Generates a Yoco checkout payload structure
   */
  async createYocoCheckout(intent: PaymentIntent) {
    // In a real production environment, this would call a backend function
    // that interacts with the Yoco Secret Key to generate a checkoutId.
    console.log('Initiating Yoco Strategic Transaction:', intent);
    
    return {
      amountInCents: intent.amount * 100,
      currency: 'ZAR',
      // checkoutId: '...', // Generated by backend
    };
  },

  /**
   * Generates a PayFast form integration structure
   */
  async generatePayFastPayload(intent: PaymentIntent) {
    const merchantId = 'YOUR_MERCHANT_ID';
    const merchantKey = 'YOUR_MERCHANT_KEY';
    
    const payload = {
      merchant_id: merchantId,
      merchant_key: merchantKey,
      return_url: `${window.location.origin}/donations/success`,
      cancel_url: `${window.location.origin}/donations/cancel`,
      notify_url: 'https://your-backend-api.com/webhooks/payfast',
      name_first: intent.metadata.donorName.split(' ')[0],
      email_address: intent.metadata.donorEmail,
      amount: intent.amount.toFixed(2),
      item_name: `Donation to ATT NGO (${intent.metadata.donationType})`,
      m_payment_id: `DON-${Date.now()}`,
    };

    return payload;
  }
};
